services:
  blog_database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog_data
      MYSQL_USER: wzy
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - blog_database_data:/var/lib/mysql

  blog_backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file: .env
    expose:
      - "8000"
    depends_on:
      - blog_database

  blog_nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf        # 自定义 Nginx 配置文件
      - ./frontend/blog/dist:/usr/share/nginx/html # 挂载前端静态文件
    ports:
      - "80:80"
    depends_on:
      - blog_backend

volumes:
  blog_database_data:
