services:
  blog_database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog_data
      MYSQL_USER: wzy
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - blog_database_data:/var/lib/mysql

  blog_backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - blog_database

  blog_frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend/blog/dist:/usr/share/nginx/html
    ports:
      - "8080:8080"
volumes:
  blog_database_data:
