services:
  blog_database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog_data
      MYSQL_USER: wzy
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - blog_database_data:/var/lib/mysql
    
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    ports:
      - "5555:5555"  # Flower 默认在 5555 端口运行
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis

  blog_backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file: .env
    expose:
      - "8000"
    depends_on:
      - blog_database
      - redis

  blog_nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf        # 自定义 Nginx 配置文件
      - ./frontend/blog/dist:/usr/share/nginx/html # 挂载前端静态文件
    ports:
      - "80:80"
    depends_on:
      - blog_backend

volumes:
  blog_database_data:
